lib/storex_web/router.ex
defmodule StorexWeb.Router do
  use StorexWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug StorexWeb.Plugs.Cart
    plug StorexWeb.Plugs.ItemsCount
    plug StorexWeb.Plugs.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StorexWeb do
    pipe_through :browser

    get "/", BookController, :index
    get "/books/:id", BookController, :show
    resources "/carts", CartController, singleton: true, only: [:show, :create, :delete]
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete], singleton: true
  end
end

lib/storex_web/views/layout_view.ex
defmodule StorexWeb.LayoutView do
  use StorexWeb, :view

  def items_count(conn) do
    StorexWeb.Plugs.ItemsCount.get(conn)
  end
end

lib/storex_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Storex · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <div class="top-bar">
        <div class="top-bar-left">
          <%= link to: Routes.book_path(@conn, :index) do %>
            <img src="<%= Routes.static_path(@conn, "/images/logo.svg") %>" alt="Storex logo"/>
          <% end %>
        </div>
        <div class="top-bar-right">
          <ul class="dropdown menu" data-dropdown-menu>
            <%= if @current_user do %>
              <li>
                <a href="#"><%= @current_user.full_name %></a>
                <ul class="menu">
                  <li><%= link "Sign out", to: Routes.session_path(@conn, :delete), method: :delete %></li>
                </ul>
              </li>
              <%= if items_count(@conn) do %>
                <li>
                  <%= link to: Routes.cart_path(@conn, :show), class: "tiny button" do %>
                    Cart <span class="alert badge"><%= items_count(@conn) %></span>
                  <% end %>
                </li>
              <% end %>
            <% else %>
              <li><%= link "sign up", to: Routes.user_path(@conn, :new) %></li>
              <li><%= link "sign in", to: Routes.session_path(@conn, :new) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </header>
    <div class="grid-container fluid">
      <br>
      <%= unless is_nil(get_flash(@conn, :info)) do %>
        <p class="success label" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= unless is_nil(get_flash(@conn, :error)) do %>
        <p class="alert label" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>
      <%= render @view_module, @view_template, assigns %>
    </div>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>